### ISSUE TITLE
Class 'ViewsCounter_Plugin' not found

### ISSUE THREAD

**Issue by Keep-Dream** [Liupaperbox/Rorical#2]
如题，除了首页都提示

**Comment by Rorical** [comment]
可能是我的readme写的不够清楚？需要安装ViewsCounter这个插件才可以使用，在[这里](https://github.com/Quarkay/Typecho-ViewsCounter)下载

**Comment by Keep-Dream** [comment]
抱歉抱歉。真没仔细看。已修复
